### ISSUE TITLE
3.0.0 release notes

### ISSUE THREAD

**Issue by 0xdeafcafe** [Kiyozz/electron-esbuild#30]
Hey! Really great work on this project, so nice to be able to use esbuild over webpack. However, could you do a GitHub release for 3.0.0 to see the changes? I'm hesitant to update blindly incase there are breaking changes.

**Comment by Kiyozz** [comment]
Oh I miss the github release. Changelogs are in CHANGELOG.md and are up to date!

**Comment by 0xdeafcafe** [comment]
Not sure how I missed that, cheers!
