### ISSUE TITLE
Unable to start dev server in yarn v3 workspaces

### ISSUE THREAD

**Issue by alii** [Kiyozz/electron-esbuild#31]
It's unable to find `node_modules/.bin/electron` as it was hoisted to the root of the workspace. Is it possible to allow for us to configure this?
![image](https://user-images.githubusercontent.com/25351731/139563980-f8ce3785-3ccb-4e87-94b8-aa8a61ae61f6.png)

**Comment by alii** [comment]
Was able to get it working by adding
```json
"installConfig": {
	"hoistingLimits": "dependencies"
},
```
to my `package.json` in the desktop app package (**not** the root `package.json`).

**Comment by Kiyozz** [comment]
Is your solution acceptable? Currently, only pnp is not supported with this.

**Comment by alii** [comment]
I guess it works but it would be nice to hoist all node modules since it simply moves all of the dependencies into this workspace rather than just `electron`. Thank you for all your hard work 🥰
