### ISSUE TITLE
ECONNREFUSED when running development

### ISSUE THREAD

**Issue by zacksiri** [Kiyozz/electron-esbuild#32]
Hey I just setup a new project and tried running the development using `npm run dev` 

I seem to be getting this error 

```
Error: connect ECONNREFUSED ::1:9081
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 9081
}
```

**Comment by zacksiri** [comment]
Switched to Node 16 (from 17) and it's working

**Comment by Kiyozz** [comment]
It seems that Node 17 is switching to ipv6 automatically when quering localhost. I had this problem in another project too.
