### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) for both index.js and index.css

### ISSUE THREAD

**Issue by MuratOzsoyler** [Kiyozz/electron-esbuild#34]
Hi,

`npm run dev` starts electron, loads `index.html` but nothing is shown on the page. Error shown in the title written to the console for `index.js` and `index.css`. On any source change the app restarts but the page is blank again.

`electron-esbuild` version is 4.0.0.

One thing I noticed is `main.js` and `preload.js` are copied to both `dist/main` and `dist/renderer` directories but `index.js` and `index.css` are not. `index.html` is copied to `dist/renderer` too. Presumably that is the cause of being able to load html but not to load js and css.

Thanks in advance.

**Comment by Kiyozz** [comment]
Hi, can you share me a repository?

**Comment by MuratOzsoyler** [comment]
Thank you for the reply.

Here it is: https://github.com/MuratOzsoyler/test-electron-esbuild.git

**Comment by Kiyozz** [comment]
Let me check it later. I thini found one possible solution.

**Comment by Kiyozz** [comment]
Ok, this is a regression from electron-esbuild@4

Thanks to you, I'll fix it for electron-esbuild@4.0.1.

**Comment by Kiyozz** [comment]
Fixed in [v4.0.1](https://github.com/Kiyozz/electron-esbuild/releases/v4.0.1)

**Comment by MuratOzsoyler** [comment]
Working as expected now.

Thank you for your efforts and building this awesome tool. I'll play with it for sometime I suppose.

Regards...
