### ISSUE TITLE
HTTP 404 error when loading index.css

### ISSUE THREAD

**Issue by MuratOzsoyler** [Kiyozz/electron-esbuild#35]
Still gives 404 error for `index.css`. Just copying to `dist/renderer` does not work. 

To solve I `require`d it in JavaScript code. This is OK but confusing for newcomers since esbuild docs says that `.css` loader is always enabled and no need for `import` or `require`.

**Comment by Kiyozz** [comment]
Indeed, because it is not in the renderer entryPoints. I fixed the templates in [v2.0.2](https://github.com/Kiyozz/electron-esbuild/releases/tag/%40electron-esbuild%2Fcreate-app%40v2.0.2) of create-app
