### ISSUE TITLE
Feature request: Allow command line arguments to be passed through to app when using `dev`

### ISSUE THREAD

**Issue by beorn** [Kiyozz/electron-esbuild#38]
Electron apps sometimes needs to accept command line arguments, and while this works as normal if the app is packaged, it doesn't work if it is spawned using `electron-esbuild dev` - currently any arguments passed is swallowed and not passed on to the main process.

I think the relevant lines are https://github.com/Kiyozz/electron-esbuild/blob/34f142a47dd4e3fd4a6cf3f7c6760b0e6be98d20/packages/electron-esbuild/src/commands/dev.mts#L44

It may be useful to see how [electron-webpack's dev server gets around this](https://github.com/electron-userland/electron-webpack/blob/41057bb1c1341cacc2df8180225c28c2cabfc3d3/packages/electron-webpack/src/dev/dev-runner.ts#L65) - I guess by using the `ELECTRON_ARGS` env variable to avoid "polluting" the command line args any more than necessary.

**Comment by Kiyozz** [comment]
Thanks! electron-webpack's dev-runner.ts will be so much helpful!
