### ISSUE TITLE
Question: How can I use electron-esbuild on a project that is already created?

### ISSUE THREAD

**Issue by GHKazza** [Kiyozz/electron-esbuild#42]
### Already created project.

I have a project that is already created, I want to install `electron-esbuild` to **"increase/improve"** the **startup time** of my application.

`npm init @electron-esbuild/app` is for creating a **new folder project**, because of that, it's not what I'm looking for. If someone can help me please :)

**Comment by Kiyozz** [comment]
Do you have any repository for me to check the level of complexity of your project?

I could make basic instructions to migrate to electron-esbuild.

**Comment by GHKazza** [comment]
**Repository:** https://github.com/GHKazza/AxieCore

I am a rookie developer in Javascript, if you see useless things in my code, I'm sorry in advance
