### ISSUE TITLE
Support vite 3.x in peer-deps

### ISSUE THREAD

**Issue by beorn** [Kiyozz/electron-esbuild#46]
Currently getting "unmet peer dep" when using electron-esbuild with latest vite.

**Comment by Kiyozz** [comment]
Indeed, I was aware of vite 3!

I just need to look for breakings that could interfer with electron-esbuild.

**Comment by Kiyozz** [comment]
Coming in 6.0.0

**Comment by Kiyozz** [comment]
Published in 6.0.0
