### ISSUE TITLE
App generator is still on electron-esbuild 6.0

### ISSUE THREAD

**Issue by robeady** [Kiyozz/electron-esbuild#50]
Firstly I just wanted to say thank you for what a superb library this seems to be. Definitely the best template/boilerplate/wrapper that I've tried in the javascript world. Everything seems to do just what is required and no more than necessary, it's a rare treat :)

---

I noticed that `yarn create @electron-esbuild/app` did not give me the latest versions of things. I thought it might be helpful to describe my experience updating manually...

The template I used was the svelte/vite/typescript one.

I tried to upgrade everything to latest (`yarn upgrade --latest`). Versions diff:

![image](https://user-images.githubusercontent.com/9981949/212447747-5db4f241-d775-4cca-9122-32e48dab6dc0.png)

This almost worked except for one snag:
```
✘ [ERROR] [plugin externalize-deps] Failed to resolve entry for package "@sveltejs/vite-plugin-svelte". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@sveltejs/vite-plugin-svelte"
```
I thought this seemed familiar from when I tried to bootstrap a vite svelte project by hand in the past. I noticed that the vite config file uses ES module imports so as a random guess, I renamed `vite.config.ts` to `vite.config.mts` and updated the electron-esbuild.config.yaml accordingly. This fixed the issue, but perhaps there is a better solution. 

I haven't observed any more problems so far.

**Comment by Kiyozz** [comment]
Thanks for your issue!

Indeed, I missed update all the templates when creating electron-esbuild@7.0.0.

This has been fixed in @electron-esbuild/create-app@4.0.1!
