### ISSUE TITLE
Build failes on esbuild 0.17

### ISSUE THREAD

**Issue by jonluca** [Kiyozz/electron-esbuild#51]
When running `electron-esbuild` with esbuild `0.17.x`, there is an error

```
✘ [ERROR] Invalid option in build() call: "incremental"
```

which is referencing this option https://github.com/Kiyozz/electron-esbuild/blob/8ad1d4af6ec7c28f9bd21a05bdaad167b4948ccc/packages/electron-esbuild/src/config/utils.mts#L27

**Comment by Kiyozz** [comment]
Hey! Yes indeed!

0.17.0 introduces the context API. I'll need to update for 0.17.0

Thanks for your issue.

**Comment by Kiyozz** [comment]
It was fixed by #53. Thanks, @jonluca!
